RELS_EXT_NAMESPACE = "info:fedora/fedora-system:def/relations-external#"
RELS_EXT = '{%s}' % (RELS_EXT_NAMESPACE)
RELS_EXT_MODEL_NAMESPACE = "info:fedora/fedora-system:def/model#"
RELS_EXT_MODEL = '{%s}' % (RELS_EXT_MODEL_NAMESPACE)
RDF_NAMESPACE = "http://www.w3.org/1999/02/22-rdf-syntax-ns#"
RDF = '{%s}' % (RDF_NAMESPACE)
RESULT_NAMESPACE = "http://www.fedora.info/definitions/1/0/types/"
RESULT = '{%s}' % (RESULT_NAMESPACE)
MANAGEMENT_NAMESPACE = "http://www.fedora.info/definitions/1/0/management/"
MANAGEMENT = '{%s}' % (MANAGEMENT_NAMESPACE)
DC_NAMESPACE = "http://purl.org/dc/elements/1.1/"
DC = '{%s}' % (DC_NAMESPACE)
OAI_DC_NAMESPACE = "http://www.openarchives.org/OAI/2.0/oai_dc"
OAI_DC = '{%s}' % (OAI_DC_NAMESPACE)
FOXML_NAMESPACE = "info:fedora/fedora-system:def/foxml#"
FOXML = '{%s}' % (FOXML_NAMESPACE)
XSI_NAMESPACE = "http://www.w3.org/2001/XMLSchema-instance"
XSI = '{%s}' % (XSI_NAMESPACE)
TV_NAMESPACE = "http://humtv.byu.edu/tvinfo/namespace/"
TV = '{%s}' % (TV_NAMESPACE)
MRSS_NAMESPACE = "http://search.yahoo.com/mrss/"
MRSS = '{%s}' % (MRSS_NAMESPACE)
SPARQL_NAMESPACE = "http://www.w3.org/2001/sw/DataAccess/rf1/result"
SPARQL = '{%s}' % (SPARQL_NAMESPACE)
XML_NAMESPACE = "http://www.w3.org/XML/1998/namespace"
XML = '{%s}' % (XML_NAMESPACE)
MA_NAMESPACE = 'http://www.w3.org/ns/ma-ont'
MA = '{%s}' % (MA_NAMESPACE)
VCP_NAMESPACE = 'http://cvp.byu.edu/namespace/'
VCP = '{%s}' % (VCP_NAMESPACE)
XSPF_NAMESPACE = 'http://xspf.org/ns/0/'
XSPF = '{%s}' % (XSPF_NAMESPACE)
